sudo: false
language: go
go: 1.16.x
env:
  global:
  - GO111MODULE=on
  - DOCKER_USERNAME=docwhat
  - secure: QnEwlhHixpuYL/nSpH8KLevNhigosJAUDDkUUJtnsotpffS4a0yqcuj6M/ryH+H3JQtNDa5RA8SSe6ymlcsf5VWwSpk0OVUnF4N8FUxfI0vMemD+GOE+7sv/t+A/9KDUJon3jRLcK/D2UGhFkVNgBXuJbkAdL/bP2S9S/oe/n5MF2Bx4SBR8hwt69wEbzNGd4FGedkaZDWrcj7czSj5pc3/b29s6MqYmCnvFgIzaFS6k5Bm7kEKaHUfR2Rdvk0Yn3+O+sqhFUkeNTd8aR2cZNw5hJhXuaX6R81V99RkNyoYhKBWqa4BivgbBtAnH3bz8VCwzVCGRH+PY3wpxhU0HTn23Rl4yxB9257muf0NgykfxMD1YaCaLlu1RBxDnn9IqnwJ1Q6iZUywH+/y+5hAxiQxNUQCVEdOfmsZjbxBMrij7hdcyKRECXx5myvFOIw1O4w4xEtZ9S2k8RpWelnUscNxgLV/44ulHXfCQ72qMwj8TPMi+TwZL95Q3WxMcP0dFYLj+FR9e8WdLJHCXNmwCCLcMO8hVBptBeb5h6y1OZ5gctAAACNa4imy/i5sYSdhdQ1zVLhyu1b+6knYUDHyX+aJ11PvT51FmZQTvXDiA/2cAdy1s5YVSY+sgzRoqbi0G+HGT2eWjTUGxR5Ks7bVr9W3aBjg6stL+Q5h86pfKWOs=
notifications:
  email:
    on_success: never
    on_failure: always
install:
- "./script/bootstrap"
script:
- "./script/test"
- "./script/lint"
before_deploy:
- "./script/docker-login"
after_deploy:
- curl -sSf -X POST 'https://hooks.microbadger.com/images/docwhat/go-importd/nH_22PPe-nH2mYs66L0BRGDQsr4='
deploy:
  skip_cleanup: true
  provider: script
  script: curl -sSfL https://git.io/goreleaser | bash
  on:
    tags: true
    repo: docwhat/go-importd
    condition: "$TRAVIS_OS_NAME = linux"
