sudo: false
language: go
go: 1.7
notifications:
  email:
    on_success: never
    on_failure: always
before_install:
  - go version
install:
  - ./script/bootstrap
script:
  - ./script/test
  - ./script/lint
  - ./script/build
  - ls -lh
  - 'grep --color TODO: *.go'
