#!/bin/bash
#
# Sets up all the dependencies, etc. so you can build and test.

set -euo pipefail

root="$(cd "${BASH_SOURCE%/*}/.." && pwd)"

indent() {
	sed 's/^/    /'
}

for cmd in trunk gotestsum; do
	printf "Verifying %s works...\n" "${cmd}"
	printf "$ script/%s --version\n" "${cmd}" | indent
	"${root}/script/${cmd}" --version | indent
done

# EOF
