# A GitHub Action to be used to build a docker image.
name: Docker image

on:
  push:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: docker
  cancel-in-progress: true

permissions: read-all

jobs:
  docker_image:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      CGO_ENABLED: 0

    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Install Go
        uses: actions/setup-go@v5

      - name: Build program
        run: |
          go build -o go-importd .

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest
# EOF
