name: Go Tests
# This is meant to be used from other workflows.
# e.g.
#
# jobs:
#   ...
#   gotestsum:
#     name: Go Tests
#     uses: ./.github/workflows/gotestsum.yaml

on: [workflow_dispatch, workflow_call]

permissions: read-all

jobs:
  gotestsum:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      CGO_ENABLED: 0

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5

      - name: Install Dependencies
        run: |
          go mod download

      - name: Install gotestsum
        run: |
          go install gotest.tools/gotestsum@latest

      - name: Install Trunk
        uses: trunk-io/trunk-action/setup@v1

      - name: GoTestSum
        run: |
          gotestsum --junitfile=junit.xml

      - name: Upload results
        if: "!cancelled()"
        uses: trunk-io/analytics-uploader@main
        with:
          junit-paths: junit.xml
          org-slug: docwhat-github
          token: ${{ secrets.TRUNK_API_TOKEN }}
        continue-on-error: true
